name: Mermaid Diagrams to PNG

on:
  workflow_dispatch:
  push:
    paths:
      - 'Docs/tccii/diagramas/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Convert diagrams to PNG
      run: |
        for f in Docs/tccii/diagramas/*.mmd; do
          filename=$(basename "$f")
          extension="${filename##*.}"
          filename="${filename%.*}"
          docker run --rm -v "$(pwd)/Docs/tccii/diagramas:/data" minlag/mermaid-cli -i "/data/$filename.$extension" -o "/data/$filename.png" --scale 5
        done

    - name: Upload PNG files
      uses: actions/upload-artifact@v2
      with:
        name: diagramas
        path: Docs/tccii/diagramas/*.png
